[package]
name = "aries-vcx-backchannel"
version = "0.1.0"
edition = "2018"
authors = ["Absa Group Limited", "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
description = "Backchannel for aries-vcx"

[dependencies]
actix-web = "3.3.2"
ctrlc = "3.1.6"
derive_more = "0.99.14"
clap = "3.0.0-beta.2"
hyper = { version = "0.14", features = ["client", "http1", "runtime", "tcp", "stream"] }
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
log = "0.4"
env_logger = "0.8.1"
once_cell = "1.5.2"
pickledb = "0.4.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
futures-util = "0.3.15"
futures = "0.3.15"
libvcx = { git = "https://github.com/hyperledger/aries-vcx", rev = "a2a1ea1" }
